version: '3'

services:
  app:
    image: dockerfile 
    container_name: your_python_app_container_name
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - your_network_name
    
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2 # You can use the desired version
    container_name: your_elasticsearch_container_name
    environment:
      - discovery.type=single-node # For development, a single node is usually sufficient
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - your_network_name

networks:
  your_network_name:
    driver: bridge

volumes:
  elasticsearch_data: