# Author: Anthony Soronnadi

version: '3.4'

services:
  app:
    image: tonysoro/qa_docker_image:latest
    container_name: qa_flask_app
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
    depends_on:
      elasticsearch:
        condition: service_healthy  # App waits for Elasticsearch to be healthy
    networks:
      - qa_network
    ports:
      - "8080:8080"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: qa_elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - qa_network
    ports:
      - "9200:9200"
    healthcheck:  # Health check for Elasticsearch
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 3

  streamlit:
    build: 
      context: .  # Path to your source code
      dockerfile: Dockerfile  # Name of the Dockerfile
    image: qa_streamlit_image:latest
    container_name: qa_streamlit_app
    depends_on:
      app:
        condition: service_started  # Streamlit waits for App to start
    networks:
      - qa_network
    ports:
      - "8501:8501"

networks:
  qa_network:
    driver: bridge

volumes:
  elasticsearch_data: